on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
          registry-url: https://npm.pkg.github.com/
          scope: "@kmylo"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
